server:
  port: 10086
  context-path: /
  tomcat:
    uri-encoding: UTF-8

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preparation?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

#头像路径
userImageFilePath: /opt/preparation/userImages/
# D://userImages/
# /opt/preparation/userImages

#文章图片路径
articleImageFilePath: /opt/preparation/articleImages/
# D://articleImages/
# /opt/preparation/articleImages

# lucene保存路径
lucenePath: /opt/preparation/lucene/
# C://lucene
# /opt/preparation/lucene

# redis
redis:
  #Matser的ip地址
  hostName: 127.0.0.1
  #端口号
  port: 6379
  #最大空闲数
  maxIdle: 100
  #最大连接数
  maxTotal: 200
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 1000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true

#支付宝支付配置
# APPID 商户appid
# RSA_PRIVATE_KEY 私钥 pkcs8格式的
# notify_url 服务器异步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
# return_url 页面跳转同步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问 商户可以自定义同步跳转地址
# URL 请求网关地址
# CHARSET 编码
# FORMAT 返回格式
# ALIPAY_PUBLIC_KEY 支付宝公钥
# SIGNTYPE RSA2

alipay:
  appid: 2016091100484467
  rsa_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCAracHQXMrtRukMQIRwlLl4D9CzSFnHllgWrQRkX50401jsyadMq0+hdiVUlif8SeNpb+zu24nnzSeUe9YC5O+zrgfzT9fb4UciP2pAIzTbQZjg6P2mZF/Io+UKsONhbSwBg2DP5OYyCIy1PtbrE/daGL98HEC3qLT4fPuVRrwYZetpQCU84X4k4ezUU/zjvbF7ARwFkhWVh9Y0MhlbGyc+FRbr2WisjI6VQIc3VzF4R430e9gMIz5k8wpjrYxuKgDq9npni2S0caBbKG1wI7vjhIfhvBqkXWSQkDLnn8mYw55ajwo/lfDuEbcN66i26eOStlVL4UPxtJAmGiwyLpLAgMBAAECggEAQ70mpIcr3eJlPrYd5MNraF/4bW4XG3W6jyKwkF8LNvVBlC6HMVGwKa3EKjdDOE93BvYuSKtufaUtyfpQCQVvLY8dFoCxz8ehRzhGcGU9vT8zkceG1RZapZbIBrPMZf/w8oj9LA6X4GHavu+nssau9FszYYLluyEAjpHwG5Lpr4ivMCBkMOVPXSAvlQqiT/MTA1U6vJJ0grRlTH0/Ydh0WWaAXX84a4P+I0uaEf6TS3yCAaPRal3pIBFH/a4vQmDo1cTuLEh2PTLF2+4fwaK0qXb3oSdE4tri7ftG1mjUgIuahNi73ShB0Vc8L8Imz8KI598zAze8JMpkBu3bvsg0AQKBgQDT7OtJxiwzTVuOhMLh2kJh3vxO34wbXc9r+XBgcqmgpbHnmYG9dKlA9wjQ1WowkyWRTmppBWw7k649zcUEhs9hVS/8hZA2NHuntOLCfHueq/M22t7PZr7odjea+JX0OaviuMbsyEw4D0Xsi6G8/HZM+8dDD+vpk9LxBQhLLCyQywKBgQCbcJblTv11nXrHyIaZWtMp6dBKjPgbTUnxfRkkfV+G0yHJAe/B7DqOm6VBae9Cj/4GcK117LbRGfRWPTrU5R1fU6V6bMLiSFXNAeAv5h01RYHbWzj80V2+G1AYeFwiBXBq/+x4BuE0rXa7+ShIXTjMJO4uKSpS4VMe3uJmvJbMgQKBgDWqhVrFSGQlbs4EaKVw8+Z85T/D9GLpuqEJJaAG6VW5H/gaM3SamlHNPPpFUQLEAHtvdBrsOKBNoY4dEYs36EQpomE8IWzYlYe+kr3VcCiaOpjljA7RYf7UEPi5gp+6CwD68cT8Y/C+TWK9aVPGSt7r02X0HjWkLYLDV3pR0WdJAoGASWNI+w7mQAeQFo8obXMiS6Gmw+v2n/1HsgpcOowu89rvEpYleqtrojT+OvonCogtaSD95LVUQzk70ROrmSRrT7yQXlLHWErKp7YBANxmYeZlPwm8yDCZT85ZbJQ2+6ERyJL4NFsbLOHRM0KZsEDDNi8hfQ3We7cCpYqZ3eOgVwECgYBIwB45eDHMYIoPf89vo7u1WcjeWzrSmDDPMHeHDKwtvbfMuSvmDDZ+VoZmS10SyKoNSKROf1xf1BNTEZ99429vHnM9OSnwWylWvoRE+VNm0lXo6TQnjMI65aFjYidu/CHrMxt0xc7nNRjEChHHsACVqDN4tNFFuWVJ1Ihvv1RPgQ==
  notify_url: https://qqzsh.top:9999/alipay/sy
  return_url: https://qqzsh.top:9999/alipay/success
  url: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAssX/n1+S1h+0BwovW1YFgamHXXUzEU4iXVrvQOeImLTpCUSi5j2jQB+aEDoW2VNzTj8KX5XxyNqaiifQ4QgjzP5KICOOxYg4/nVCWToBhOdpypVS4EiCHSP9VXNNRtLghJpXN9eXYdbDNtKFse84eW9nQwt/RrGaNeFSH+//qKid1B01BK2XzzR3WfRP4rAoS63O0YYDejuVBfaLX5Z178tuqUt7aStlHm7RLzboQEUjZZVschUmwPmx6vgKFwbuNTXCy5GOQRM+SdQxVqWmxurMNUUfAFN3M2yB/oiPVkYRnZ6qZsOn1Q2bjW7lUfApu0tRADGVNvDSZmXzBxBpsQIDAQAB
  signtype: RSA2
